# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

- ignore: {within: TestGen} # Generated code
- ignore: {name: Unused LANGUAGE pragma, within: Partial} # CPP
- ignore: {name: Eta reduce} # Not sure I agree
- ignore: {name: Use lambda-case} # not available on GHC 7.4
- ignore: {name: Use fmap, within: Control.Monad.Extra} # Only a Monad context
- ignore: {name: Use void, within: Control.Monad.Extra} # Only a Monad context
